version: '3.8'

services:
    mongo:
        container_name: mevn_mongo
        platform: ${DOCKER_PLATFORM:-linux/amd64}
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./data/mongo:/data/db
    mongo-express:
        container_name: mevn_mongo_express
        platform: ${DOCKER_PLATFORM:-linux/amd64}
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mevn_mongo
            ME_CONFIG_BASICAUTH_USERNAME: user
            ME_CONFIG_BASICAUTH_PASSWORD: abc123
networks:
    mevn_network:
        driver: bridge
